# Generated by Django 2.2.6 on 2019-11-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_abbreviation', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
