# Generated by Django 2.2.6 on 2019-11-05 15:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('article_number', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=100)),
                ('cost_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('cost_per_unit', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.MeasurementUnit')),
            ],
        ),
    ]
